### ISSUE TITLE
Make tabs on Plan summary page configurable

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/forests#156]
- [ ] Allow editor to configure the titles of the image tabs on the plan summary page.
- [ ] Add a description field to each tab
- [ ] Bug fix: Show plan map when no images have been uploaded to the plan.

**Comment by ygoex** [comment]
- Implement the GeoLayer entity here.
- Pulling the data from BRMS

**Comment by peacog** [comment]
Closed as outdated due to #357
