### ISSUE TITLE
Mapbox key

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/forests#206]
The Mapbox base layer is no longer available on maps. We need to configure a valid mapbox key in settings.php i.e.

`$config['farm_map_mapbox.settings']['api_key'] = 'key goes here';
`

**Comment by peacog** [comment]
A Mapbox token has been created for FMS and configured in settings.overrides.php

**Comment by LeScruf** [comment]
@peacog - can we close this if there is nothing outstanding?

**Comment by peacog** [comment]
Yes, go ahead and close it @LeScruf
