### ISSUE TITLE
Security warning: Couldn't write .htaccess file.

### ISSUE THREAD

**Issue by pcambra** [National-Forestry-Authority/forests#210]
We're getting:

```Security warning: Couldn't write .htaccess file. Please create a .htaccess file in your ../config/sync directory which contains the following lines: ```

According to SBIT this needs to be included in the repo:

```
# Deny all requests from Apache 2.4+.
<IfModule mod_authz_core.c>
  Require all denied
</IfModule>

# Deny all requests from Apache 2.0-2.2.
<IfModule !mod_authz_core.c>
  Deny from all
</IfModule>

# Turn off all options we don't need.
Options -Indexes -ExecCGI -Includes -MultiViews

# Set the catch-all handler to prevent scripts from being executed.
SetHandler Drupal_Security_Do_Not_Remove_See_SA_2006_006
<Files *>
  # Override the handler again if we're run later in the evaluation list.
  SetHandler Drupal_Security_Do_Not_Remove_See_SA_2013_003
</Files>

# If we know how to do it safely, disable the PHP engine entirely.
<IfModule mod_php7.c>
  php_flag engine off
</IfModule>
<IfModule mod_php.c>
  php_flag engine off
</IfModule>

```

**Comment by pcambra** [comment]
We should also check brms and farmers.

**Comment by peacog** [comment]
It was a permissions problem. The .htaccess file could not be created because the directory did not have write permission. I changed the permissions of config/sync to 777 and the problem was resolved.
The same error was showing on brms. It has been fixed too. Farmers did not have the problem

**Comment by pcambra** [comment]
@peacog that's a security risk, please revert that and include the file in the repo instead.

**Comment by peacog** [comment]
@pcambra the config directory is outside the web root. Is that still a security risk?

**Comment by peacog** [comment]
@pcambra in any case I've changed the permissions back to 755. The .htaccess file has been created so I don't think we need to add it to the repo

**Comment by peacog** [comment]
config/sync/.htaccess is now tracked in the repo
