### ISSUE TITLE
Create schema for upcoming changes to forest management plan

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/forests#279]
New fields and functionality for Plans and CFRs have been defined in the following documents:

[FMAP budget - CFR level.pdf](https://github.com/National-Forestry-Authority/forests/files/13486799/FMAP.budget.-.CFR.level.pdf)
[FMAP demo - management task form.pdf](https://github.com/National-Forestry-Authority/forests/files/13486795/FMAP.demo.-.management.task.form.pdf)
[FMAP demo - task budget form.pdf](https://github.com/National-Forestry-Authority/forests/files/13486798/FMAP.demo.-.task.budget.form.pdf)
[FMAP demo.pdf](https://github.com/National-Forestry-Authority/forests/files/13486796/FMAP.demo.pdf)
[FMAP simplified data model relationships - Nov23.pdf](https://github.com/National-Forestry-Authority/forests/files/13486800/FMAP.simplified.data.model.relationships.-.Nov23.pdf)
[FMAP structure - Oct23.xlsx](https://github.com/National-Forestry-Authority/forests/files/13486797/FMAP.structure.-.Oct23.xlsx)

- [ ] #297 
- [ ] #298 
- [ ] #299 
- [ ] #300

**Comment by LeScruf** [comment]
Hi @ygoex & @peacog - attached is a work-in-progress for the new natural forest management plan format. It is quite long, but  am hoping that 90% of it is very straight-forward, especially with the new form format that has been developed. We will have to work through the existing task management functionality on the system and also develop a straight-forward way for task budgeting. We can go through this anytime - please let me know.

[FMAP structure - Oct23.xlsx](https://github.com/National-Forestry-Authority/forests/files/13070272/FMAP.structure.-.Oct23.xlsx)

**Comment by ygoex** [comment]
Phase 1 done.
