### ISSUE TITLE
New FMAP - Management task

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/forests#299]
On the Management task form add the CFR, program/activity and sub-activity dropdowns described in the specification document.
Load the programs from the Program Tab field group config entities of the selected CFR. See #297 for more details

Specification

[FMAP demo - management task form.pdf](https://github.com/National-Forestry-Authority/forests/files/13486795/FMAP.demo.-.management.task.form.pdf)

**Comment by peacog** [comment]
@LeScruf on the management task form you included an Add task link for adding multiple tasks. We recommend not doing that. Each individual management task should be added by clicking on the Add management task button on the plan's Management tab.

**Comment by peacog** [comment]
This is finally ready to test @LeScruf 
In plans and CFRs you can add programs/activities that are then selectable in the management task form.
There's a related ticket about displaying the sub-activity in the list of management tasks #346

**Comment by LeScruf** [comment]
Ok great - I took a look and it seems ok. I think the proof of things working well will be when the data starts being entered.
