### ISSUE TITLE
Deprecate plantation plan types

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/forests#311]
Delete the [Forest plantation](https://forests.stg.envs.utils.nfa.go.ug/admin/structure/plan-type) plan type. In our code there are a couple of places where we present an option to select either 'natural' or 'plantation'. We should remove the plantation option. This happens in 

- ForestPlanInventoryForm::defaultSettings
- Forest::buildFieldDefinitions
- farm_nfa_forest_form_alter

Check code for other references to the plantation plan type and make sure we don't break anything when we delete the plan type

**Comment by peacog** [comment]
We've removed the plantation plan type @LeScruf

**Comment by LeScruf** [comment]
Great - thanks.
