### ISSUE TITLE
Plan types should show status on the form

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/forests#314]
Show the status field on the plan type form display https://forests.stg.envs.utils.nfa.go.ug/admin/structure/plan-type/natural/edit/form-display

**Comment by ygoex** [comment]
Required by #312.

**Comment by pcambra** [comment]
I've included this one on https://github.com/National-Forestry-Authority/forests/pull/321

**Comment by LeScruf** [comment]
@ygoex - can you explain / remind me what I'm supposed to be thinking about / reviewing here? Thanks!

**Comment by peacog** [comment]
Sorry @LeScruf we didn't explain this very well in the description. It's just the status field on the plan edit form. It used to be hidden and we're put it back again.


![Image](https://github.com/National-Forestry-Authority/forests/assets/1312689/aded6dee-87f3-4f60-a5e7-a844f2897cc4)

**Comment by LeScruf** [comment]
Looking good! Thks.
