### ISSUE TITLE
Some CFRs not shown on parent range map

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/forests#317]
Some CFRs are missing from range maps. For example [Bugoma CFR](https://forests.stg.envs.utils.nfa.go.ug/asset/322) should be shown on the [Budongo System Range](https://forests.stg.envs.utils.nfa.go.ug/asset/800) map but it is not there. 
There are also some missing CFRs on the Achwa River Range map, such as Lalak, Lamwo and Agoro Agu

**Comment by peacog** [comment]
This is fixed

**Comment by LeScruf** [comment]
It is indeed fixed!
