### ISSUE TITLE
Dont allow management task if CFR is not in plan

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/forests#355]
When a CFR does not belong to a plan it should not be possible to add a management task for it.
Hide the Add Management Task button.

![Image](https://github.com/National-Forestry-Authority/forests/assets/1312689/8291e93b-fa5e-4fb7-a6cb-2653ba65d1f8)

**Comment by peacog** [comment]
Ready to test @LeScruf

**Comment by LeScruf** [comment]
@peacog - I think this may still be a work-in-progress - see https://forests.stg.envs.utils.nfa.go.ug/asset/278/management ?

**Comment by peacog** [comment]
That one's OK @LeScruf. On staging Mabira CFR is in the Mabira (Test) plan, for test purposes https://forests.stg.envs.utils.nfa.go.ug/asset/278
![image](https://github.com/National-Forestry-Authority/forests/assets/1312689/3ff1f9ae-f6f6-489c-b902-d19e3acdf386)

**Comment by LeScruf** [comment]
@peacog - oops - that was embarrassing - apologies - I wasn't expecting Mabira to have a plan ... and didn't check. Looks good - works as you said it would! Thanks!
