### ISSUE TITLE
Plan image gallery

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/forests#357]
- On the plan we have a multivalue image field for uploading map images
- Remove the existing image tabs (deprecates #156)

![Image](https://github.com/National-Forestry-Authority/forests/assets/1312689/93aa6979-8f31-4002-9d87-6b48f8c8c26d)

- Create a map image gallery/slider and display it on another plan tab
- Tab order is Summary, Maps, GFW, Management, Budget, Inventory, Enrichment

**Comment by peacog** [comment]
@LeScruf I've added the Maps tab and a simple image slider with previous and next arrows.

**Comment by LeScruf** [comment]
@peacog - would it be possible to center the image in the gallery? I think this would then make it a little more intuitive to use and scroll the images?

**Comment by peacog** [comment]
Images are now centered @LeScruf https://forests.stg.envs.utils.nfa.go.ug/plan/1/maps

**Comment by LeScruf** [comment]
Looking good! Thanks!
