### ISSUE TITLE
Private files migration

### ISSUE THREAD

**Issue by pcambra** [National-Forestry-Authority/forests#68]
Private files migration might be failing because the files are not moved yet? 

```
  farm_migrate_file_private Migration - 39 failed.  
```

**Comment by mstenta** [comment]
We can check to see if any of these are necessary to migrate. They may have just been tests. Or they may be KML file uploads that were used in the old database to import areas.

**Comment by pcambra** [comment]
@mstenta how can we check what those files are?

**Comment by ygoex** [comment]
This migration happened very long ago.
